### ISSUE TITLE
Script error in installation

### ISSUE THREAD

**Issue by fachat** [IBM/cloud-native-starter#16]
Running the install scripts I get the following error:
<pre>
cloud-native-starter$ scripts/deploy-web-api-java-jee.sh
scripts/deploy-web-api-java-jee.sh: 8: scripts/deploy-web-api-java-jee.sh: Syntax error: "(" unexpected
</pre>
on an Ubuntu 16.04 host

**Comment by fachat** [comment]
I guess it's about replacing "sh" with "bash" in the shebang line

**Comment by nheidloff** [comment]
Thanks for creating the issues @fachat. @Harald-U will return tomorrow and take a look at the Linux related ones.

**Comment by Harald-U** [comment]
@fachat You are right, it is the shebang "#!/bin/sh". Interstingly, it does work on Fedora. I replaced all occurences. Thnaks for pointing it out!!!
