### ISSUE TITLE
Cannot connect to demo

### ISSUE THREAD

**Issue by fachat** [IBM/cloud-native-starter#19]
After running the installation process with all scripts for a local minikube, I cannot connect to the app:
<pre>
Firefox can’t establish a connection to the server at 192.168.99.100:31380.
</pre>
Istio tells me something about "pending" on the external IP:
<pre>
istio-system   istio-ingressgateway     LoadBalancer   10.110.187.239   <pending>     15020:30332/TCP,80:31380/TCP,443:31390/TCP,31400:31400/TCP,15029:30827/TCP,15030:32327/TCP,15031:32182/TCP,15032:30530/TCP,15443:30640/TCP   9h
</pre>
Not sure what I would have to change to template.local.env to run the example locally - I just copied it over.
kubectl get pod gives:
<pre>
NAME                          READY   STATUS    RESTARTS   AGE
articles-54d8979866-p7thc     2/2     Running   0          8m37s
authors-799f865c55-8nz7z      2/2     Running   0          4m29s
web-api-v1-6f84d7c856-d7plv   2/2     Running   0          4m47s
web-app-77866cb8b5-ndlvv      2/2     Running   0          4m16s
</pre>

Any ideas?

**Comment by nheidloff** [comment]
I don't think the 'pending' status is an issue. I see this as well. We use the Istio Ingress port 31380 instead.

Is 192.168.99.100 your Minikube IP?
```
minikube ip
```

Can you invoke the endpoints of the other three services? Run 'scripts/show-urls.sh' to get the URLs.

Can you check whether the web app throws an error?
```
pod=$(kubectl get pods | grep web-app | awk ' {print $1} ')
kubectl logs $pod web-app
```

**Comment by nheidloff** [comment]
You also ran "scripts/deploy-istio-ingress-v1.sh" right?

**Comment by Harald-U** [comment]
@fachat 
The 'pending' status is to be expected (https://istio.io/docs/tasks/traffic-management/ingress/ingress-control/  -> If the EXTERNAL-IP value is <none> (or perpetually <pending>), your environment does not provide an external load balancer for the ingress gateway. In this case, you can access the gateway using the service’s node port.)
As to why you cannot connect I have no idea. You did run the "scripts/deploy-istio-ingress-v1.sh" as Niklas suggested?

**Comment by Harald-U** [comment]
I am closing this, please reopen if problem persists
