### ISSUE TITLE
Retrieving some value by using "ibmcloud ks cluster-get" needs en_US locale

### ISSUE THREAD

**Issue by EunKyung-Kim** [IBM/cloud-native-starter#24]
Hi,

Actually, this issue is related to several script files.
When you retrieve the value of specific configuration  by using "ibmcloud ks cluster-get" in a script file, ibmcloud should have the locale configuration with en_US.
Normally ibmcloud uses OS environment language as its locale. So, in Korean OS env, that script occurs the error. For example, 26 line of cluster-get-config.sh is as follows.

STATE=$(ibmcloud ks cluster-get $CLUSTER_NAME -s | awk '/^State:/ {print $2}')

In Korea OS env, ibmcloud outputs "상태" instead of "State". So, we can't get the value of "State".
Therefore, in my case, I should have performed "ibmcloud config --locale en_US".

I suggest that document mentions this as prerequisite to support people in non-English.

Regards,
EunKyung Kim

**Comment by Harald-U** [comment]
This is a very valid issue, thank you for pointing it out! I have added a statement in the prereq section of the IKSDeployment and OpenShiftIKSDeployment document, I think these are the ones who could have a potential problem.
