### ISSUE TITLE
Cannot create cluster on IBM cloud

### ISSUE THREAD

**Issue by reators** [IBM/cloud-native-starter#28]
I followed the instructions on [Deployment in IBM cloud](https://github.com/IBM/cloud-native-starter/blob/master/documentation/IKSDeployment.md) but I'm failing on the first script

    iks-scripts/create-iks-cluster.sh

The script seems to run successfully, but neither of

    ibmcloud ks cluster ls

nor

    ibmcloud ks cluster-get cloud-native -s

show anything about the new cluster.
I was able the create the account through http://ibm.biz/nheidloff and followed all the instructions to set up the local environment.

OS: Win10 with git-bash.

**Comment by thomassuedbroecker** [comment]
Hello @reators, 

thanks your your feedback. 

Pls, can you try to follow also the "more" simple workshop: [Deploying Java Microservices to Kubernetes on IBM Cloud](https://github.com/IBM/cloud-native-starter/tree/master/workshop-one-service)  ?

There is also a workshop: Let’s get started with cloud native Java applications on Kubernetes [Let’s get started with cloud native Java applications on Kubernetes ](https://github.com/IBM/cloud-native-starter/tree/master/workshop)

I only found one typo in step one "git clone https://github.com/nheidloff/cloud-native-starter.git" replace "nheidloff" with "IBM".

Information related to windows 10:  [Definition of a Dockerfile to use bash scripts on a Windows 10 machine for our Cloud-Native-Starter workshop](https://suedbroecker.net/2019/08/27/definition-of-a-dockerfile-to-use-bash-scripts-on-a-windows-10-machine-for-our-cloud-native-starter-workshop/)

Greetings, 

Thomas

**Comment by Harald-U** [comment]
Can you check in the IBM Cloud Web Console, in the Kubernetes section under Clusters, if a cluster has been created? (Select All Resources and All Locations)

**Comment by reators** [comment]
Hello Harald-U,

thanks for your reply.

> Can you check in the IBM Cloud Web Console, in the Kubernetes section under Clusters, if a cluster has been created? (Select All Resources and All Locations)

I cannot find a Kubernetes section under https://cloud.ibm.com/account.
Maybe you could provide a link?
My guess is that I need some kind of upgrade to the account (https://cloud.ibm.com/kubernetes/catalog/cluster/create talks about this ("Für Ihren aktuellen Kontotyp stehen keine kostenfreien Cluster zur Verfügung. Führen Sie zur Erstellung eines neuen Standardclusters ein Upgrade für Ihr Konto durch.")

> The script creates a logfile in iks-scripts: create-iks-cluster.log. Something helpful in there?

<details>
  <summary>create-iks-cluster.log</summary>

```
Unsetting api endpoint...
OK

No api endpoint set.
Setting api endpoint...
OK

API endpoint: https://cloud.ibm.com
Not logged in. Use 'C:\Program Files\IBM\Cloud\bin\ibmcloud.exe login' to log in.
API endpoint: https://cloud.ibm.com
Authenticating...
OK

Targeted account Holger Kummert's Account (67d966a9a0cf4ae9b7733a44b65e091a)

Targeted region us-south

                      
API endpoint:      https://cloud.ibm.com   
Region:            us-south   
User:              holger.kummert@attempto.eu   
Account:           Holger Kummert's Account (67d966a9a0cf4ae9b7733a44b65e091a)   
Resource group:    No resource group targeted, use 'C:\Program Files\IBM\Cloud\bin\ibmcloud.exe target -g RESOURCE_GROUP'   
CF API endpoint:      
Org:                  
Space:                

Tip: If you are managing Cloud Foundry applications and services
- Use 'C:\Program Files\IBM\Cloud\bin\ibmcloud.exe target --cf' to target Cloud Foundry org/space interactively, or use 'C:\Program Files\IBM\Cloud\bin\ibmcloud.exe target --cf-api ENDPOINT -o ORG -s SPACE' to target the org/space.
- Use 'C:\Program Files\IBM\Cloud\bin\ibmcloud.exe cf' if you want to run the Cloud Foundry CLI with current IBM Cloud CLI context.

WARNING: The 'ibmcloud ks region-get' command is deprecated and will be removed. For more information, see http://ibm.biz/iks-cli-v1

             
Region:   us-south   
The 'machine-type' flag was not specified. So a free cluster will be created.
Creating cluster...
FAILED
To create clusters, you need an IBM Pay-As-You-Go or Subscription account with access to infrastructure portfolio. To set up your account, see 'http://ibm.biz/account'. (E0129)

Incident ID: bbca5b40-fb79-4766-a2a6-2db78a67aa16
```
</details>

Yes, goes in the same direction as my above guess.

**Comment by reators** [comment]
Hello @thomassuedbroecker,

thanks for your reply. On following

> Pls, can you try to follow also the "more" simple workshop: [Deploying Java Microservices to Kubernetes on IBM Cloud](https://github.com/IBM/cloud-native-starter/tree/master/workshop-one-service) ?

I found on https://github.com/IBM/cloud-native-starter/blob/master/workshop-one-service/0-create-kubernetes-cluster.md the hint:
`In order to create a free Kubernetes cluster, you need a promo or feature code.`

Do you have an idea on how to get such a code?

**Comment by Harald-U** [comment]
Thats easy, can you contact me via email (uebele@de.ibm.com) then I can send you a code and instructions

**Comment by reators** [comment]
Thanks for providing the code. `create-iks-cluster.sh` works now.
