### ISSUE TITLE
Can't make everything to work in Minikube

### ISSUE THREAD

**Issue by juangon** [IBM/cloud-native-starter#38]
Hi!
First of all, thanks very much for all of this code, it's very useful!

Second, it seems I can't get the reactive examples working.
For example, when deploying kafka through strimzi operator, kafka cluster pods doesn't start (I opened and issue here https://github.com/strimzi/strimzi-kafka-operator/issues/2449 ).

But..when I decreased the replica number to 1, it seems to be running fine, BUT it starts failing after deploying and invoking the web-app-reactive URL.

Do you know what can be happening? I am using latest minikube, Kubernetes and strimzi operator versions.

Thanks very much!

Here are logs attached:

[logs-from-kafka-in-my-cluster-kafka-0(1).txt](https://github.com/IBM/cloud-native-starter/files/4159098/logs-from-kafka-in-my-cluster-kafka-0.1.txt)
[logs-from-zookeeper-in-my-cluster-zookeeper-0(1).txt](https://github.com/IBM/cloud-native-starter/files/4159099/logs-from-zookeeper-in-my-cluster-zookeeper-0.1.txt)

**Comment by Harald-U** [comment]
Hola, Juan! 

Thanks for trying out our pet project!

I just ran through the setup again and it works for me.  Are you using a fresh Minikube cluster? The symptoms you describe sound a bit like the cluster is under memory or CPU pressure.  I just created a new cluster in Minikube using cpus: 2, memory: 8192, disk-size: 30g and when everything is installed and running, Kafka, Postgres, and the 4 services, there is still enough resources according to minikube dashboard.

Can you try again, if possible with a fresh Minikube instance? You could use minikube profile to create a new one if you need to keep the existing profile.

Just out of curiosity: which version of Minikube, which OS, which Hypervisor?

**Comment by juangon** [comment]
Thanks  @Harald-U!
Yes, I am using the script provided in reactive/scripts to start minikube etc, so it has 4 CPU and 8GB RAM.

Using minikube 1.6.2, Ubuntu 18, Virtualbox VM.

BTW while I was writing this I started minikube again and now it seems to be working (adding authors and it's showing in frontend).

Do you know why starting again could have fixed the problem?

**Comment by Harald-U** [comment]
Juan, thats good news!

Minikube is pushing the limits with a single node. I have the luxury of running it on a notebook with 32 GB of memory so I tend to give 12 to 16 GB to Minikube (during the first start). I also gibe it 4 of my 8 vCPUs.  

FYI: minikube 1.6.2, Fedora 30, KVM (virt-manager)

I am going to close this issue. Feel free to contact us again! And thanks for your feedback!!!
