### ISSUE TITLE
Java Persistence

### ISSUE THREAD

**Issue by joymallyac** [IBM/cloud-native-starter#42]
This repo shows how to gain persistence using JPA and 'Db2 on Cloud'. But this will definitely affect the performance. Is there a way to do this in memory and not using any external database?

**Comment by thomassuedbroecker** [comment]
@joymallyac Yes, but this project is designed to be as simple as possible for the setup and to use the free Kubernetes Lite Cluster on IBM Cloud in our Workshops, [so we don’t use persistence-volumes in Kubernetes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/). Performance testing of persistence isn't in scope of that example Project. We like to be as less responsible as possible related to managing operations and setup tasks, and we follow the strategy: "Why to setup an own databases, if they are as a service available?"  I hope that helps.
