### ISSUE TITLE
3 Create a free Kubernetes Cluster - Service is name "kubernetes Service"

### ISSUE THREAD

**Issue by hajo62** [IBM/cloud-native-starter#48]
![image](https://user-images.githubusercontent.com/15800980/92399501-ae18c200-f12a-11ea-918a-b3b920d5c282.png)

**Comment by hajo62** [comment]
Name and screenshot outdated

**Comment by Harald-U** [comment]
Thanks for pointing this out, Hajo.
I made the changes, inclusing the following screenshots where the UI changed as well
