### ISSUE TITLE
Keine Umgebungsvariablen, sondern einzusetzende Werte

### ISSUE THREAD

**Issue by hajo62** [IBM/cloud-native-starter#49]
Hier sind die Umgebungsvariablen nicht gesetzt. 
$REGISTRY/$REGISTRY_NAMESPACE
Man soll hier die Werte einsetzen, das steht dort aber nicht

<img width="1046" alt="grafik" src="https://user-images.githubusercontent.com/15800980/92455624-38f8cb80-f1c2-11ea-9dfd-c9943da74e9a.png">

**Comment by thomassuedbroecker** [comment]
Thanks HaJo, fixed!
